server:
  port: 8085

spring:
  application:
    name: hr-management-service
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eventuate
    username: root
    password: rootpassword

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: 127.0.0.1:9092
#    topic:
#      employee-leave: hr.employee.create
#    consumer:
#      group-id: employees
#      auto-offset-reset: earliest

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'